name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build
      run: go build -o filevault ./cmd/filevault
    
    - name: Test
      run: go test -v ./...
    
    - name: Test Coverage
      run: |
        go test -v ./test/unit/... || echo "Unit tests completed"
        go test -v ./test/integration/... || echo "Integration tests completed"

  build-cross-platform:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build all platforms
      run: |
        chmod +x ./scripts/build.sh
        ./scripts/build.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: build/