name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build all platforms
      run: |
        chmod +x ./scripts/build.sh
        ./scripts/build.sh
    
    - name: Create archive
      run: |
        cd build
        zip -r ../filevault-binaries.zip ./*
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          filevault-binaries.zip
          build/*